# Generated by Django 5.2.7 on 2025-10-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='initial_message',
            field=models.TextField(blank=True, help_text='Initial context message sent to AI before student speaks', null=True),
        ),
    ]
