# Generated by Django 4.2.25 on 2025-10-14 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Curriculum title', max_length=255)),
                ('description', models.TextField(help_text='Curriculum description')),
                ('image', models.ImageField(blank=True, help_text='Curriculum image', null=True, upload_to='curriculum/images/')),
                ('country', models.CharField(help_text='Country for this curriculum', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
                'ordering': ['country', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Label title', max_length=255)),
                ('order', models.IntegerField(default=0, help_text='Display order within curriculum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
                'ordering': ['curriculum', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Topic title', max_length=255)),
                ('description', models.TextField(help_text='Topic description')),
                ('image', models.ImageField(blank=True, help_text='Topic image', null=True, upload_to='curriculum/topics/')),
                ('content_link', models.URLField(help_text='Link to topic content', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Display order within label')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='curriculum.label')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['label', 'order', 'title'],
            },
        ),
    ]
