# Generated by Django 4.2.25 on 2025-10-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='description_ar',
            field=models.TextField(help_text='Curriculum description', null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='description_en',
            field=models.TextField(help_text='Curriculum description', null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='title_ar',
            field=models.CharField(help_text='Curriculum title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='title_en',
            field=models.CharField(help_text='Curriculum title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='title_ar',
            field=models.CharField(help_text='Label title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='title_en',
            field=models.CharField(help_text='Label title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_ar',
            field=models.TextField(help_text='Topic description', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_en',
            field=models.TextField(help_text='Topic description', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_ar',
            field=models.CharField(help_text='Topic title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title_en',
            field=models.CharField(help_text='Topic title', max_length=255, null=True),
        ),
    ]
